### ISSUE TITLE
Port to 1.7.10

### ISSUE THREAD

**Issue by BraveCaperCat** [McJtyMods/RFToolsControl#187]
Please port this mod so it works with 1.7.10

**Comment by McJty** [comment]
1.7.10 is ancient! Please move to the present. I have no time to maintain my mods on so many versions so I focus on 1.16 and 1.18 only

**Comment by BraveCaperCat** [comment]
I don't care about how old a minecraft version is, i only care about what mods run on it(I would like these mods on 1.7.10)

**Comment by McJty** [comment]
Well as I said. I really don't have the time. 1.7.10 is too different from current Minecraft. I basically would have to write these mods from scratch and I really can't do that

**Comment by BraveCaperCat** [comment]
I would **help** you, If i knew how to make a **minecraft mod** (And UPDATE IT) as **RFTools** is one of my favorite **mods,** I am a great **coder** but i am almost useless at finding **bugs**

**Comment by BraveCaperCat** [comment]
And you are a very nice dev @McJty!

**Comment by BraveCaperCat** [comment]
TrainCraft Doesn't work on 1.12.2
