### ISSUE TITLE
Minecraft crashing when opening processor

### ISSUE THREAD

**Issue by PlanetSat0rn** [McJtyMods/RFToolsControl#195]
Issue description: minecraft keeps crashing when i use the processor

Steps to reproduce: idk

Versions:
* Minecraft: 1.19.2
* Forge: 43.2.11
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 7.2.5
* RFTools: 4.1.7
* RFTools Control: 6.1.4

Possibly incompatible mods and versions: 
![image](https://github.com/McJtyMods/RFToolsControl/assets/109532054/98518c6a-e0ce-46df-99f7-c072f35eff07)

couldnt bother typing in the text since it would take time

Relevant logs, if any: https://pastebin.com/ccBTBzvs

issue could also be that im missing the rftools storage mod

**Comment by McJty** [comment]
yes you are. It's not optional here

**Comment by PlanetSat0rn** [comment]
figured that out a while ago

please put rftools storage in the required dependencies section of the mod
